spring.application.name=demo


server.port=8080
spring.web.resources.static-locations=classpath:/browser/

logging.level.org.springframework.security.web.csrf=TRACE


springdoc.swagger-ui.tagsSorter=alpha
application-description=@project.description@

application-version=@project.version@

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.use-fqn=true
springdoc.paths-to-exclude=/apilogout

#springdoc.swagger-ui.csrf.enabled=true
#springdoc.swagger-ui.csrf.header-name=X-XSRF-TOKEN
