spring.application.name=demo
#in a more serious application, do not store secrets in plain text in this file
#pass them in using environment variables or a secrets manager


okta.domain=okta.com
okta.base.url=https://${okta.tenant.id}.${okta.domain}
okta.oauth2.issuer=${okta.base.url}/oauth2/default


okta.oauth2.scopes=openid, profile, email, offline_access, foo, bar

server.port=8081
spring.web.resources.static-locations=classpath:/browser/

#logging.level.org.springframework.security.web.csrf=TRACE
logging.level.ROOT=WARN
logging.level.org.springframework.security.web=DEBUG
logging.level.org.springframework.security.web.csrf=TRACE
logging.level.org.springframework.web.cors=TRACE
logging.level.org.apache.coyote.http11=DEBUG
logging.level.org.apache.catalina.filters=DEBUG
logging.level.org.springframework.web.filter=TRACE
logging.level.org.springframework.security.config=TRACE

logging.file.name=logs/@project.artifactId@.log

springdoc.swagger-ui.tagsSorter=alpha
application-description=@project.description@

application-version=@project.version@

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.use-fqn=true
springdoc.paths-to-exclude=/apilogout




#example values
#actual values will appear by system properties
#-Dokta.tenant.id=trial-4304447
#-Dokta.oauth2.client-id=0oayosn2wqzGADFdq697
#-Dokta.oauth2.client-secret=PDw1IyOOcJMA_n6H6RqCm82fvPXlqduoZlm2djR9pWGvYYVnbXROT-J4h6q1DWE5


