<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>eg</groupId>
    <artifactId>bff-demos</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>oidc.bff</artifactId>
  	<name>spring.oidc.bff</name>
	<description>spring.oidc.bff</description>
	<dependencies>
		
		<dependency>
  <groupId>com.okta.spring</groupId>
  <artifactId>okta-spring-boot-starter</artifactId>
  <version>3.0.8</version>
</dependency>
</dependencies>
		

	<build>
	
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			
		 
		</plugins>
	</build>

	<profiles>
		<profile>
			<id>e2e</id>
			<properties>
				<swagger.e2e.url>http://localhost:8081</swagger.e2e.url>
			</properties>
			<build>
				<plugins>
					<plugin>
						<groupId>org.springframework.boot</groupId>
						<artifactId>spring-boot-maven-plugin</artifactId>
						<configuration>
							<systemPropertyVariables>
								<febaseurl>${febaseurl}</febaseurl>
								<okta.tenant.id>${okta.tenant.id}</okta.tenant.id>
								<okta.oauth2.client-id>${okta.oauth2.client-id}</okta.oauth2.client-id>
								<okta.oauth2.client-secret>${okta.oauth2.client-secret}</okta.oauth2.client-secret>
							</systemPropertyVariables>
						</configuration>
						<executions>
							<execution>
								<id>spring-boot-start</id>
								<phase>pre-integration-test</phase>
								<goals>
									<goal>start</goal>
								</goals>
							</execution>
							<execution>
								<id>spring-boot-stop</id>
								<phase>post-integration-test</phase>
								<goals>
									<goal>stop</goal>
								</goals>
							</execution>
						</executions>
					</plugin>

					<plugin>
						<groupId>com.github.eirslett</groupId>
						<artifactId>frontend-maven-plugin</artifactId>
						<version>1.15.4</version>
						<configuration>
							<nodeVersion>${nodeVersion}</nodeVersion>
							<installDirectory>${nodeInstallDir}</installDirectory>
						</configuration>
						<executions>
							<execution>
								<id>install node and npm - playwright</id>
								<phase>pre-integration-test</phase>
								<goals>
									<goal>install-node-and-npm</goal>
								</goals>
							</execution>
							<execution>
								<id>npm install - swagger-bff-e2e</id>
								<phase>pre-integration-test</phase>
								<goals>
									<goal>npm</goal>
								</goals>
								<configuration>
									<workingDirectory>${project.basedir}/swagger-bff-e2e</workingDirectory>
									<arguments>install</arguments>
								</configuration>
							</execution>
							<execution>
								<id>playwright install chromium</id>
								<phase>pre-integration-test</phase>
								<goals>
									<goal>npx</goal>
								</goals>
								<configuration>
									<workingDirectory>${project.basedir}/swagger-bff-e2e</workingDirectory>
									<arguments>playwright install chromium</arguments>
								</configuration>
							</execution>
							<execution>
								<id>playwright test</id>
								<phase>integration-test</phase>
								<goals>
									<goal>npx</goal>
								</goals>
								<configuration>
									<workingDirectory>${project.basedir}/swagger-bff-e2e</workingDirectory>
									<arguments>playwright test --headed</arguments>
									<environmentVariables>
										<SWAGGER_UI_URL>${swagger.e2e.url}</SWAGGER_UI_URL>
										<OKTA_TENANT_ID>${okta.tenant.id}</OKTA_TENANT_ID>
										<TEST_USER_EMAIL>${okta.test.user.email}</TEST_USER_EMAIL>
										<TEST_USER_PASSWORD>${okta.test.user.password}</TEST_USER_PASSWORD>
									</environmentVariables>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>


</project>